name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build and push Docker images to ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker-compose -f Docker-compose.yml build --progress=plain
        docker tag chat-app_chat-frontend:latest $ECR_REGISTRY/$ECR_REPOSITORY/chat-frontend:$IMAGE_TAG
        docker tag chat-app_auth-backend:latest $ECR_REGISTRY/$ECR_REPOSITORY/auth-backend:$IMAGE_TAG
        docker tag chat-app_ws-backend:latest $ECR_REGISTRY/$ECR_REPOSITORY/ws-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY/chat-frontend:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY/auth-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY/ws-backend:$IMAGE_TAG

   
