name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Create credential Amazon ECR
      id: ecr-credential-setup
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'false'

    - name: Build and push Docker images to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker-compose -f Docker-compose.yml build --progress=plain
        docker tag chat-app_chat-frontend:latest $ECR_REGISTRY/$ECR_REPOSITORY/frontend:$IMAGE_TAG
        docker tag chat-app_auth-backend:latest $ECR_REGISTRY/$ECR_REPOSITORY/auth-backend:$IMAGE_TAG
        docker tag chat-app_ws-backend:latest $ECR_REGISTRY/$ECR_REPOSITORY/ws-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_REGISTRY/$ECR_REPOSITORY/frontend:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_REGISTRY/$ECR_REPOSITORY/auth-backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_REGISTRY/$ECR_REPOSITORY/ws-backend:$IMAGE_TAG

   
